name: "go-licenses"
on: 
  push:
    paths:
      - 'go.mod'
    branches:
      - master
  workflow_dispatch: 

jobs:
  go-licenses:
    runs-on: ubuntu-latest
    name: Run go-licenses
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Get google/go-licenses package
        run: go install github.com/google/go-licenses@latest
        shell: bash
      - name: Run go-licenses and save deps
        run: go-licenses save ./... --save_path=dependencies --force
      - name: Push licenses
        run: |
          git config --global user.name "${{ vars.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ vars.CI_COMMIT_EMAIL }}"
          git add dependencies
          git diff --quiet --exit-code --cached dependencies
          if [ $? -eq 1 ]
          then
            git commit -m "ci(licenses): updated licenses"
            git push
          else
            exit 0
          end
